[project]
name = "chmat"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastexcel>=0.17.2",
    "loguru>=0.7.3",
    "openai>=2.8.1",
    "polars>=1.35.2",
    "python-dotenv>=1.2.1",
    "qdrant-client>=1.16.0",
]
